#ifndef PREDEFINEDTAGS_H
#define PREDEFINEDTAGS_H


#define LEFT_FRONT_WHEEL_SPEED_SENSOR "wss_lf"
#define RIGHT_FRONT_WHEEL_SPEED_SENSOR "wss_rf"
#define CENTER_REAR_WHEEL_SPEED_SENSOR "wss_cr"
#define LEFT_REAR_WHEEL_SPEED_SENSOR "wss_lr"
#define RIGHT_REAR_WHEEL_SPEED_SENSOR "wss_rr"
#define VOLTAGE_SENSOR "vot"
#define THROTTLE_PEDAL "tpd"
#define BRAKE_PEDAL "bpd"


#endif // PREDEFINEDTAGS_H
